### ISSUE TITLE
Consider using Themis

### ISSUE THREAD

**Issue by vladimir-ivanov-epam** [epam/Android-Secure-Storage#1]
In order to skip complex crypto usage we can consider using the external library for that: 

https://github.com/cossacklabs/themis

Please, do a research and conclude if the lib fits our needs.

**Comment by vixentael** [comment]
Themis provides stronger cryptography and data protection by using AES-GCM-256 under the hood, relying on BoringSSL and having built-in key derivation function (KDF). For developers Themis is easy to use, without a need to understand cryptography and dig into cryptographic parameters, like key length or IV manipulations. 

I think using Themis will increase security and decrease complexity of Android Secure Storage code.

1. 
[SafeStorageM](https://github.com/epam/Android-Secure-Storage/blob/master/app/src/main/java/com/epam/android/keystore/SafeStorageM.java#L60) can be re-written using [Themis Secure Cell](https://github.com/cossacklabs/themis/wiki/Secure-Cell-cryptosystem), which provides strong symmetric encryption.

```
// encrypt
SecureCell cell = new SecureCell(password);
SecureCellData cellData = cell.protect(data);

// store encrypted data as SecureCellData or as byte[] whatever fits better
byte[] protectedData = cellData.getProtectedData();
```

```
// decrypt
SecureCell cell = new SecureCell(password);
byte[] data = cell.unprotect(cellData);
```

See more in Secure Cell docs for [Android](https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto#secure-cell).

2. 
[Themis Secure Message](https://github.com/cossacklabs/themis/wiki/Secure-Message-cryptosystem) provides encryption and signing, in either RSA mode or ECC mode. It could be used for SafeStoragePreM.

See more in Secure Message docs for [Android](https://github.com/cossacklabs/themis/wiki/Java-and-Android-Howto#secure-message).

3. 
More examples: simple [Android and Java example project](https://github.com/cossacklabs/themis-java-examples) and [iOS-Android secret chat](https://github.com/cossacklabs/mobile-websocket-example).

**Disclaimer**
I'm one of the maintainers of Themis, but not an Android developer myself, my understanding of Android best practices is limited, so let me know if you have any usability concerns.

**Comment by vixentael** [comment]
Any updates, guys?

**Comment by vladimir-ivanov-epam** [comment]
Not yet, we will get back in several weeks.

**Comment by vvsevolodovich** [comment]
@vixentael Good news! We are working on using Themis in this component, expect an update in a week or so)

**Comment by vixentael** [comment]
Great job, guys!
